### PR TITLE
payload mapping testrunner

### PR DESCRIPTION
**Pull request by Yannic92**

### CODE REVIEW

**Comment by thjaeckle** [comment]
@Yannic92 and @joosdavid - the ECA check if Eclipse says the following:

> David Joos (david.joos@....com) is not covered by the necessary legal agreements in order to proceed.
Yannic Klem (yannic.klem@....com) did not include the "Signed-off-by footer" which is required for all commits made by a contributor.

Could you please fix that so that we can proceed with this PR?

**Comment by Yannic92** [comment]
@thjaeckle Thank you. Fixed the missing sign-off

**Comment by DoktorDaveJoos** [comment]
Guess it's ready to merge

**Comment by thjaeckle** [comment]
No, it's not, the Eclipse ECA check fails again:

     David Joos (david.joos@****.com) did not include the "Signed-off-by footer" which is required for all commits made by a contributor.
     Yannic Klem (yannic.klem@****.com) did not include the "Signed-off-by footer" which is required for all commits made by a contributor.

**Comment by Yannic92** [comment]
Fixed it again. @joosdavid @DoktorDaveJoos Please pull with --rebase

**Comment by Yannic92** [comment]
Will still require some renaming and javadoc adaptions

**Pull request merged**
